/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The fallback language used if language is not in the preferred_language_list
    /// </summary>
    /// <value>The fallback language used if language is not in the preferred_language_list</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FallbackLanguage
    {
        /// <summary>
        /// Enum En for value: en
        /// </summary>
        [EnumMember(Value = "en")]
        En = 1,

        /// <summary>
        /// Enum Es for value: es
        /// </summary>
        [EnumMember(Value = "es")]
        Es = 2,

        /// <summary>
        /// Enum Nl for value: nl
        /// </summary>
        [EnumMember(Value = "nl")]
        Nl = 3,

        /// <summary>
        /// Enum De for value: de
        /// </summary>
        [EnumMember(Value = "de")]
        De = 4,

        /// <summary>
        /// Enum Fr for value: fr
        /// </summary>
        [EnumMember(Value = "fr")]
        Fr = 5,

        /// <summary>
        /// Enum It for value: it
        /// </summary>
        [EnumMember(Value = "it")]
        It = 6,

        /// <summary>
        /// Enum Ja for value: ja
        /// </summary>
        [EnumMember(Value = "ja")]
        Ja = 7,

        /// <summary>
        /// Enum Cmn for value: cmn
        /// </summary>
        [EnumMember(Value = "cmn")]
        Cmn = 8,

        /// <summary>
        /// Enum Pt for value: pt
        /// </summary>
        [EnumMember(Value = "pt")]
        Pt = 9
    }

}
