/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IngestionIntegrationIdAudioPost409ResponseResult
    /// </summary>
    [DataContract(Name = "_ingestion_integration__id__audio_post_409_response_result")]
    public partial class IngestionIntegrationIdAudioPost409ResponseResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IngestionIntegrationIdAudioPost409ResponseResult" /> class.
        /// </summary>
        /// <param name="contentType">The uploaded data&#39;s detected [content type](https://www.iana.org/assignments/media-types/media-types.xhtml).</param>
        /// <param name="hashSha256">The uploaded data&#39;s SHA256 hash.</param>
        /// <param name="uuid">The uploaded data&#39;s UUID in the Theta Lake system.</param>
        public IngestionIntegrationIdAudioPost409ResponseResult(string contentType = default(string), string hashSha256 = default(string), string uuid = default(string))
        {
            this.ContentType = contentType;
            this.HashSha256 = hashSha256;
            this.Uuid = uuid;
        }

        /// <summary>
        /// The uploaded data&#39;s detected [content type](https://www.iana.org/assignments/media-types/media-types.xhtml)
        /// </summary>
        /// <value>The uploaded data&#39;s detected [content type](https://www.iana.org/assignments/media-types/media-types.xhtml)</value>
        /*
        <example>video/mp4</example>
        */
        [DataMember(Name = "content_type", EmitDefaultValue = false)]
        public string ContentType { get; set; }

        /// <summary>
        /// The uploaded data&#39;s SHA256 hash
        /// </summary>
        /// <value>The uploaded data&#39;s SHA256 hash</value>
        /*
        <example>5179a08ff65e6388a466447dd1c6ee5fae0c9b080ec3a61e21cd6818ed1d8624</example>
        */
        [DataMember(Name = "hash_sha256", EmitDefaultValue = false)]
        public string HashSha256 { get; set; }

        /// <summary>
        /// The uploaded data&#39;s UUID in the Theta Lake system
        /// </summary>
        /// <value>The uploaded data&#39;s UUID in the Theta Lake system</value>
        /*
        <example>5883caa5-c428-5998-dcda-b51a457c021f</example>
        */
        [DataMember(Name = "uuid", EmitDefaultValue = false)]
        public string Uuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IngestionIntegrationIdAudioPost409ResponseResult {\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  HashSha256: ").Append(HashSha256).Append("\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
