/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PostIdentityRiskRequest
    /// </summary>
    [DataContract(Name = "PostIdentityRiskRequest")]
    public partial class PostIdentityRiskRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostIdentityRiskRequest" /> class.
        /// </summary>
        /// <param name="datumId">The datum ID with the risky behavior in it.</param>
        /// <param name="risky">Indicates if identity is behaving in a risky fashion.</param>
        /// <param name="comment">Comment for the identity&#39;s risk in the datum.</param>
        public PostIdentityRiskRequest(int? datumId = default(int?), bool risky = default(bool), string comment = default(string))
        {
            this.DatumId = datumId;
            this.Risky = risky;
            this.Comment = comment;
        }

        /// <summary>
        /// The datum ID with the risky behavior in it
        /// </summary>
        /// <value>The datum ID with the risky behavior in it</value>
        /*
        <example>215779</example>
        */
        [DataMember(Name = "datum_id", EmitDefaultValue = true)]
        public int? DatumId { get; set; }

        /// <summary>
        /// Indicates if identity is behaving in a risky fashion
        /// </summary>
        /// <value>Indicates if identity is behaving in a risky fashion</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "risky", EmitDefaultValue = true)]
        public bool Risky { get; set; }

        /// <summary>
        /// Comment for the identity&#39;s risk in the datum
        /// </summary>
        /// <value>Comment for the identity&#39;s risk in the datum</value>
        /*
        <example>John is sharing Personal Identifying Information of a client</example>
        */
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostIdentityRiskRequest {\n");
            sb.Append("  DatumId: ").Append(DatumId).Append("\n");
            sb.Append("  Risky: ").Append(Risky).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
