/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LegalHoldCasesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LegalHoldCasesApiTests : IDisposable
    {
        private LegalHoldCasesApi instance;

        public LegalHoldCasesApiTests()
        {
            instance = new LegalHoldCasesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LegalHoldCasesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LegalHoldCasesApi
            //Assert.IsType<LegalHoldCasesApi>(instance);
        }

        /// <summary>
        /// Test CasesGet
        /// </summary>
        [Fact]
        public void CasesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? pageToken = null;
            //int? max = null;
            //var response = instance.CasesGet(pageToken, max);
            //Assert.IsType<GetCasesResponse>(response);
        }

        /// <summary>
        /// Test CasesIdGet
        /// </summary>
        [Fact]
        public void CasesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.CasesIdGet(id);
            //Assert.IsType<GetCaseResponse>(response);
        }
    }
}
