/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoriesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoriesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoriesInner
        //private CategoriesInner instance;

        public CategoriesInnerTests()
        {
            // TODO uncomment below to create an instance of CategoriesInner
            //instance = new CategoriesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoriesInner
        /// </summary>
        [Fact]
        public void CategoriesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoriesInner
            //Assert.IsType<CategoriesInner>(instance);
        }

        /// <summary>
        /// Test the property 'CategoryGroupId'
        /// </summary>
        [Fact]
        public void CategoryGroupIdTest()
        {
            // TODO unit test for the property 'CategoryGroupId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Deprecated'
        /// </summary>
        [Fact]
        public void DeprecatedTest()
        {
            // TODO unit test for the property 'Deprecated'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DetectionMediaTypes'
        /// </summary>
        [Fact]
        public void DetectionMediaTypesTest()
        {
            // TODO unit test for the property 'DetectionMediaTypes'
        }

        /// <summary>
        /// Test the property 'DetectionType'
        /// </summary>
        [Fact]
        public void DetectionTypeTest()
        {
            // TODO unit test for the property 'DetectionType'
        }

        /// <summary>
        /// Test the property 'DisabledAt'
        /// </summary>
        [Fact]
        public void DisabledAtTest()
        {
            // TODO unit test for the property 'DisabledAt'
        }

        /// <summary>
        /// Test the property 'Disclaimer'
        /// </summary>
        [Fact]
        public void DisclaimerTest()
        {
            // TODO unit test for the property 'Disclaimer'
        }

        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Fact]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }

        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Fact]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }

        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Fact]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'RiskType'
        /// </summary>
        [Fact]
        public void RiskTypeTest()
        {
            // TODO unit test for the property 'RiskType'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusColor'
        /// </summary>
        [Fact]
        public void StatusColorTest()
        {
            // TODO unit test for the property 'StatusColor'
        }

        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Fact]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }

        /// <summary>
        /// Test the property 'ToDate'
        /// </summary>
        [Fact]
        public void ToDateTest()
        {
            // TODO unit test for the property 'ToDate'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
