/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrgUnit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrgUnitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrgUnit
        //private OrgUnit instance;

        public OrgUnitTests()
        {
            // TODO uncomment below to create an instance of OrgUnit
            //instance = new OrgUnit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrgUnit
        /// </summary>
        [Fact]
        public void OrgUnitInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrgUnit
            //Assert.IsType<OrgUnit>(instance);
        }

        /// <summary>
        /// Test the property 'AllowAnonymousViaSharedLinks'
        /// </summary>
        [Fact]
        public void AllowAnonymousViaSharedLinksTest()
        {
            // TODO unit test for the property 'AllowAnonymousViaSharedLinks'
        }

        /// <summary>
        /// Test the property 'AnalysisSupervisionSpaces'
        /// </summary>
        [Fact]
        public void AnalysisSupervisionSpacesTest()
        {
            // TODO unit test for the property 'AnalysisSupervisionSpaces'
        }

        /// <summary>
        /// Test the property 'AuditLogRetentionPeriod'
        /// </summary>
        [Fact]
        public void AuditLogRetentionPeriodTest()
        {
            // TODO unit test for the property 'AuditLogRetentionPeriod'
        }

        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Fact]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'DefaultOrgTimezone'
        /// </summary>
        [Fact]
        public void DefaultOrgTimezoneTest()
        {
            // TODO unit test for the property 'DefaultOrgTimezone'
        }

        /// <summary>
        /// Test the property 'DeleteOnExpiration'
        /// </summary>
        [Fact]
        public void DeleteOnExpirationTest()
        {
            // TODO unit test for the property 'DeleteOnExpiration'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

        /// <summary>
        /// Test the property 'DisabledAt'
        /// </summary>
        [Fact]
        public void DisabledAtTest()
        {
            // TODO unit test for the property 'DisabledAt'
        }

        /// <summary>
        /// Test the property 'FallbackLanguage'
        /// </summary>
        [Fact]
        public void FallbackLanguageTest()
        {
            // TODO unit test for the property 'FallbackLanguage'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PreferredLanguageList'
        /// </summary>
        [Fact]
        public void PreferredLanguageListTest()
        {
            // TODO unit test for the property 'PreferredLanguageList'
        }

        /// <summary>
        /// Test the property 'PreferredLanguages'
        /// </summary>
        [Fact]
        public void PreferredLanguagesTest()
        {
            // TODO unit test for the property 'PreferredLanguages'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'UseNameMatcher'
        /// </summary>
        [Fact]
        public void UseNameMatcherTest()
        {
            // TODO unit test for the property 'UseNameMatcher'
        }

        /// <summary>
        /// Test the property 'UseOwnerOnlySpaceMatcher'
        /// </summary>
        [Fact]
        public void UseOwnerOnlySpaceMatcherTest()
        {
            // TODO unit test for the property 'UseOwnerOnlySpaceMatcher'
        }

        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
    }
}
