/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PutOrgUnitByIdRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PutOrgUnitByIdRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PutOrgUnitByIdRequest
        //private PutOrgUnitByIdRequest instance;

        public PutOrgUnitByIdRequestTests()
        {
            // TODO uncomment below to create an instance of PutOrgUnitByIdRequest
            //instance = new PutOrgUnitByIdRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PutOrgUnitByIdRequest
        /// </summary>
        [Fact]
        public void PutOrgUnitByIdRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PutOrgUnitByIdRequest
            //Assert.IsType<PutOrgUnitByIdRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AllowAnonymousViaSharedLinks'
        /// </summary>
        [Fact]
        public void AllowAnonymousViaSharedLinksTest()
        {
            // TODO unit test for the property 'AllowAnonymousViaSharedLinks'
        }

        /// <summary>
        /// Test the property 'AnalysisSupervisionSpaceIds'
        /// </summary>
        [Fact]
        public void AnalysisSupervisionSpaceIdsTest()
        {
            // TODO unit test for the property 'AnalysisSupervisionSpaceIds'
        }

        /// <summary>
        /// Test the property 'AuditLogRetentionPeriod'
        /// </summary>
        [Fact]
        public void AuditLogRetentionPeriodTest()
        {
            // TODO unit test for the property 'AuditLogRetentionPeriod'
        }

        /// <summary>
        /// Test the property 'DefaultOrgTimezone'
        /// </summary>
        [Fact]
        public void DefaultOrgTimezoneTest()
        {
            // TODO unit test for the property 'DefaultOrgTimezone'
        }

        /// <summary>
        /// Test the property 'DeleteOnExpiration'
        /// </summary>
        [Fact]
        public void DeleteOnExpirationTest()
        {
            // TODO unit test for the property 'DeleteOnExpiration'
        }

        /// <summary>
        /// Test the property 'FallbackLanguage'
        /// </summary>
        [Fact]
        public void FallbackLanguageTest()
        {
            // TODO unit test for the property 'FallbackLanguage'
        }

        /// <summary>
        /// Test the property 'PreferredLanguages'
        /// </summary>
        [Fact]
        public void PreferredLanguagesTest()
        {
            // TODO unit test for the property 'PreferredLanguages'
        }

        /// <summary>
        /// Test the property 'UseNameMatcher'
        /// </summary>
        [Fact]
        public void UseNameMatcherTest()
        {
            // TODO unit test for the property 'UseNameMatcher'
        }

        /// <summary>
        /// Test the property 'UseOwnerOnlySpaceMatcher'
        /// </summary>
        [Fact]
        public void UseOwnerOnlySpaceMatcherTest()
        {
            // TODO unit test for the property 'UseOwnerOnlySpaceMatcher'
        }
    }
}
