/*
 * Theta Lake API
 *
 * We are excited to inform you that our documentation is interactive!  If you are logged in, this means that you can not only read about the features and capabilities of our product, but also try them out directly from the documentation pages. Our interactive documentation provides a hands-on experience that allows you to test the API endpoints, experiment with the input parameters, and see the corresponding responses. This makes it easier to understand how the API works and how to integrate it into your own applications. With interactive documentation, you can save time and avoid frustration by testing the API right from the documentation pages, without having to set up a local development environment. Whether you're a seasoned developer or just starting out, our interactive documentation is the perfect tool to help you learn, experiment, and succeed with our API. 
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing QueryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryRequest
        //private QueryRequest instance;

        public QueryRequestTests()
        {
            // TODO uncomment below to create an instance of QueryRequest
            //instance = new QueryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryRequest
        /// </summary>
        [Fact]
        public void QueryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryRequest
            //Assert.IsType<QueryRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'IncludesTimestamp'
        /// </summary>
        [Fact]
        public void IncludesTimestampTest()
        {
            // TODO unit test for the property 'IncludesTimestamp'
        }

        /// <summary>
        /// Test the property 'MediaType'
        /// </summary>
        [Fact]
        public void MediaTypeTest()
        {
            // TODO unit test for the property 'MediaType'
        }
    }
}
